[package]
name = "contract_event_listener"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["macros", "rt"] }
web3 = "0.19.0"
