[package]
name = "merkle_tree_eth"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
secp256k1 = "0.31.0"
serde = "1.0.219"
serde_json = "1.0.140"
tiny-keccak = "2.0.2"
tokio = "1.45.1"
web3 = "0.19.0"
